-
 base:
    index_url: https://www.wy56.com/test/h5/keyi-wms/
    base_url: https://api.wy56.com/test/wms-api
    login_url: https://api.wy56.com/test/wms-api/system/login
    getcust_url: https://api.wy56.com/test/wms-api/order/customer/downList?custName=
    getgood_url: https://api.wy56.com/test/wms-api/wms/base/goods/list
    getinstorebilllist_url: https://api.wy56.com/test/wms-api/wms/instore/bill/list
    getinstorebillinfo_url: https://api.wy56.com/test/wms-api/wms/instore/bill/info/
    import_insotre_bill_url: https://api.wy56.com/test/wms-api/wms/instore/bill/importExcel
    userName: 上海管理
    password: 123456
    login_type: 1
    pre_auth: Bearer
    assert_str: 2000000
    import_insotre_bill_file: 入库单导入.xls
 log:
    log_name: log_
    log_level: info
    log_fomat: '[%(asctime)s] %(filename)s->%(funcname)s'